function out = createTestOutput(obj, test)
% CREATETESTOUTPUT - Creates the output text given a TestResult object
%   This function takes in the results of a MATLAB unit test and formats the display output for Gradescope. If an error
%   was thrown, it will output the first error message in the stack. If verifications failed, it will output all of
%   them. It will cut off error messages or individual verifications that are longer than the MaxOutputLength property.
%
%   If the diagnostic contained the keyword 'IMAGEFILE', it will assume that an image was output as a diagnostic. It will
%   take the string following that keyword as an image filepath and convert the image to base64 for display.
%
%   Only the 'Test Diagnostic' portion of the report is parsed into the output, which means only the messages input as 
%   the diagnostics of the verification functions will be visible to students.
%
%   If a student code errors, the function will recreate the error message from the exception and the stack.
%
%   Arguments
%       test - A matlab.unittest.TestResult object to parse the results of
%       out - A character array of the diagnostic report

arguments
    obj
    test (1, 1) {mustBeA(test, 'matlab.unittest.TestResult')}
end

out = ''; % Add default success message
if test.Incomplete
    out = parseIncompleteTest(obj, test);
elseif test.Failed
    out = parseFailedTest(obj, test);
end
% Html parsing
out(out < 32 & out ~= 10) = '�'; % Remove illegal ascii characters, exclude newline
end

function msg = parseIncompleteTest(obj, test)
% Helper function to parse test cases that were incomplete, or in other words errored.

indent = repmat(' ', 1, 4);
spacer = repmat('-', 1, 14);
prefix = sprintf(sprintf('An error occured while running your function.\n%s%s\n%sError Details:\n%s%s\n', ...
    indent, spacer, indent, indent, spacer));

% Always get out the first error report
errorCases = strcmp({test.Details.DiagnosticRecord.Event}, 'ExceptionThrown');
diagnostic = test.Details.DiagnosticRecord(find(errorCases, 1));
exception = diagnostic.Exception(1);

% Create error message based on identifier
if contains(exception.identifier, 'HWStudent')
    % Error generated directly by exception handling in TestRunner
    msg = regexprep(exception.message, '(\n)(?! {4})', '$1    '); % Add padding to existing newlines
elseif strcmp(exception.identifier, 'MATLAB:array:SizeLimitExceeded')
    % If an array size limit error was thrown with evalc, then the student function attempted to
    % output too much text to the command window (most likely unsuppressed imread or similar)
    msg = sprintf(['Matlab attempted to display or create a %s array/string and exceeded the allocated memory capacity (%s). ' ...
        'Ensure that you have suppressed your lines of code using semicolons.'], exception.arguments{1}, exception.arguments{3});
elseif strcmp(exception.identifier, 'MATLAB:unassignedOutputs')
    % If the student never assigned the function output variable, this error will be thrown.
    msg = sprintf(erase(exception.message, 'student.'));
elseif contains(exception.identifier, 'TestRunner') || ~any(contains({exception.stack.file}, '+student'))
    % Unintended error, thrown by autograder or student function not in error stack.
    msg = 'The autograder ran into an unexpected error while running your function. Please contact the HW TAs for assistance.';
    return % Exit early, no need to parse
else
    % Generic error generated by the student's code
    stuFunc = find(contains({exception.stack.file}, '+student'), 1, 'first');
    lines = readlines(exception.stack(stuFunc).file);
    lineNo = exception.stack(stuFunc).line;
    if lineNo > 0
        errorMsg = sprintf('%s\n\nError in %s (line %d)\n%s', exception.message, exception.stack(stuFunc).name, lineNo, lines(lineNo));
    else
        errorMsg = exception.message;
    end
    msg = strrep(errorMsg, newline, [newline indent]);
end
msg = regexprep(msg, '<a[^>]*>(.*?)</a>', '$1'); % Remove hyperlink (if present)
msg = sprintf('%s%s%s', prefix, indent, msg); % Add prefix and indent
% Truncate error message if too long
shouldTruncate = numel(msg) > obj.MaxOutputLength;
if shouldTruncate
    msg = msg(1:obj.MaxOutputLength);
end
% HTML Parsing
msg = strrep(msg, '\', '&#92;');
msg = strrep(msg, '&', '&amp;');
msg = strrep(msg, '<', '&lt;');
msg = strrep(msg, '>', '&gt;');
% Re-add message after to not cut off parsed characters
if shouldTruncate
    msg = sprintf('%s\n<strong>(Error Message Truncated)</strong>', msg);
end
end

function msg = parseFailedTest(obj, test)
% Helper function to parse test cases that failed, or in other words did not pass verification.
% Does not need html parsing as the toChar function handles it for us.

msg = sprintf('Verification failed in %s.\n    ----------------\n    Test Diagnostic:', extractAfter(test.Name, '/'));
for i = 1:numel(test.Details.DiagnosticRecord)
    % Temp string created in case multiple verifications were run for one test case.
    temp = test.Details.DiagnosticRecord(i).Report;
    temp = char(extractBetween(temp, sprintf('Test Diagnostic:\n    ----------------\n'), sprintf('\n    ---------------------\n    Framework Diagnostic')));
    filename = extractAfter(temp, 'IMAGEFILE:');
    if isempty(filename)
        % If not imagefile, truncate if too long
        if numel(temp) > obj.MaxOutputLength
            temp = sprintf('%s\n<strong>(Verification Truncated)</strong>', temp(1:obj.MaxOutputLength));
        end
    else
        % Image to base64 encoding
        fid = fopen(filename,'rb');
        % Skip if file cannot be read
        if fid == -1
            continue
        end
        try
            bytes = fread(fid);
            encoder = org.apache.commons.codec.binary.Base64; % base64 encoder
            base64string = char(encoder.encode(bytes))';
            size = obj.ImageSize;
            temp = [extractBefore(temp, 'IMAGEFILE:'), sprintf( ...
                ['<img src=''data:image/png;base64,%s'' width = ''%d'' height = ''%d''> \n    <em>' ...
                'Please run your function in Matlab to view your figure in higher quality.</em>'], ...
                base64string, size(1), size(2))];
            fclose(fid);
        catch E
            warning(getReport(E));
            temp = '<em>Image comparison failed to run.</em>';
        end
    end
    if isempty(temp) % If there is an issue and no output diagnostic is provided, skip output display.
        continue;
    end
    msg = sprintf('%s\n    ----------------\n%s', msg, temp);
end
end
